"""Add activation_code to user and make password nullable

Revision ID: a3291a2b086e
Revises: 51ecb5e87644
Create Date: 2025-04-20 01:13:22.397057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3291a2b086e'
down_revision: Union[str, None] = '51ecb5e87644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activation_code', sa.String(length=128), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_user_activation_code'), 'user', ['activation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activation_code'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'activation_code')
    # ### end Alembic commands ### 